In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(
    {
    'name': ['Alice', 'Kim', 'John'],
    'gender': ['F', 'M', 'M'],
    'age': [10, 11, 9],
    'grades': [100, 99, 98]
    }
)

In [3]:
df

,name,gender,age,grades
0,Alice,F,10,100
1,Kim,M,11,99
2,John,M,9,98

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
s = pd.Series(['red', 'blue', 'black'])

In [6]:
s

In [7]:
type(s)

pandas.core.series.Series

In [8]:
df['age']

In [11]:
df[['age']]

,age
0,10
1,11
2,9

In [9]:
type(df['age'])

pandas.core.series.Series

In [10]:
type(df[['age']])

pandas.core.frame.DataFrame

In [12]:
df['age'].describe()

In [13]:
df.describe()

,age,grades
count,3.0,3.0
mean,10.0,99.0
std,1.0,1.0
min,9.0,98.0
25%,9.5,98.5
50%,10.0,99.0
75%,10.5,99.5
max,11.0,100.0

In [14]:
df['age'].max()

11

In [2]:
inventory = pd.read_csv('Sloan_Inventory.csv')

In [3]:
inventory.shape

(825, 16)

In [22]:
inventory.head(5)

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
0,Analyzer,490000,Microtrac particle analyzer (3 pcs),31,337,186,457,509,946,444,621,861,442,975,735,977
1,Analyzer,490001,3300 IR gas analyzer,68,855,837,347,769,289,907,785,815,851,270,521,244
2,Analyzer,490002,TGA-7 thermogravitmetric analyzer.,90,805,590,489,536,662,237,154,240,592,474,780,864
3,Analyzer,490003,Model 911 Dew-All digital humidity analyzer.,57,178,769,438,556,717,94,832,717,545,268,47,68
4,Analyzer,490004,1000 tablet? Hardness Tester,3,154,45,859,180,729,486,862,33,955,497,20,121

In [23]:
inventory.head(50)

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
0,Analyzer,490000,Microtrac particle analyzer (3 pcs),31,337,186,457,509,946,444,621,861,442,975,735,977
1,Analyzer,490001,3300 IR gas analyzer,68,855,837,347,769,289,907,785,815,851,270,521,244
2,Analyzer,490002,TGA-7 thermogravitmetric analyzer.,90,805,590,489,536,662,237,154,240,592,474,780,864
3,Analyzer,490003,Model 911 Dew-All digital humidity analyzer.,57,178,769,438,556,717,94,832,717,545,268,47,68
4,Analyzer,490004,1000 tablet? Hardness Tester,3,154,45,859,180,729,486,862,33,955,497,20,121
5,Analyzer,490005,213 blood gas analyzer with 208 -02/01,35,441,349,820,519,309,469,31,68,603,188,82,810
6,Analyzer,490006,343 flame analyzer - parts,90,941,303,572,172,120,900,971,500,719,348,462,714
7,Analyzer,490007,513 blood gas analyzer,82,673,86,604,269,606,236,594,27,585,723,741,674
8,Analyzer,490008,9000 analyzer,22,339,879,902,530,142,442,813,8,725,185,47,743
9,Analyzer,490009,903-H moisture analog,31,767,684,279,743,231,785,987,440,816,472,343,858
10,Analyzer,490010,985-S1 electrolyte analyzer,65,858,647,361,666,731,131,431,116,481,970,11,215
11,Analyzer,490011,Analyzer,59,809,667,506,927,145,703,902,770,168,428,814,767
12,Analyzer,490012,Analyzer,78,667,923,978,942,699,524,49,808,621,229,68,566
13,Analyzer,490013,analyzer,24,150,854,188,867,172,561,971,54,974,216,340,808
14,Analyzer,490014,B-641 thermal cycler,98,917,856,437,474,928,577,752,772,721,66,918,533
15,Analyzer,490015,CA analyzer,68,247,160,593,148,473,362,298,602,231,125,195,236
16,Analyzer,490016,Creatinine analyzer.,32,201,486,905,966,519,220,184,364,270,723,72,144
17,Analyzer,490017,Ion Analyzer,72,663,139,501,179,611,602,91,906,598,7,159,196
18,Analyzer,490018,E5 300 immunoassay system with Twin Software v...,15,966,173,103,254,56,641,70,320,940,324,189,387
19,Analyzer,490019,Micro 1310 blood gas analyzer with 326-10,24,647,200,629,242,551,208,967,897,438,929,98,938
20,Analyzer,490020,Model 634 Ca/pH electrolyte analyzer. (For who...,97,310,575,367,500,270,550,215,357,304,269,963,557
21,Analyzer,490021,Model 7000 nitrogen detection system,39,879,72,159,708,935,427,579,841,689,555,321,637
22,Analyzer,490022,Model DP-247E dual sample aggregation meter.,23,244,767,292,565,907,862,9,567,789,639,524,366
23,Analyzer,490023,N Wood RF600 ser 179 analyzer,52,634,738,873,873,677,596,419,992,63,679,522,500
24,Analyzer,490024,Pal II pH and blood gas analysis system.,27,447,798,321,289,362,736,865,852,314,183,466,983
25,Analyzer,490025,Sedigraph 5000ET analyzer,18,216,996,893,31,697,153,928,664,143,947,41,941
26,Analyzer,490026,Semi-Automatic Cleveland Open Cup (ASTM D92) a...,90,275,751,159,315,459,38,342,705,833,761,290,42
27,Analyzer,490027,Seralyzer Model 5181.,48,162,932,823,340,309,795,67,903,960,66,247,776
28,Analyzer,490028,Surfsc analyzer,18,4,717,388,672,381,518,223,805,159,483,71,346
29,Analyzer,490029,tablet tester with stand,78,971,527,753,3,677,783,293,44,559,660,358,209
30,Analyzer,490030,TGA50 programmable thermo gravimetric analyzer...,89,170,842,951,179,114,223,610,379,201,183,100,633
31,Autoclave,490031,self contained steam autoclave with 16 inch di...,9,7,941,739,406,580,755,99,31,112,836,164,968
32,Autoclave,490032,OCM tabletop autoclave. Chamber 8 inches diame...,83,595,381,566,67,995,60,365,389,66,535,35,279
33,Autoclave,490033,"OCR autoclave. 9"" diameter x 18"".",10,475,86,464,859,439,968,547,740,321,123,932,458
34,Autoclave,490034,Validat 10.,44,998,91,886,158,681,73,344,749,867,352,294,226
35,Autoclave,490035,Validar Plus tabletop sterilizer.,0,514,801,695,632,114,499,65,849,271,877,212,430
36,Autoclave,490036,Model STME with 0 to 60 minute timer. Chamber ...,5,465,480,613,892,687,869,826,279,907,145,668,473
37,Autoclave,490037,16x26 cylindrical autoclave with generator.,37,648,725,414,804,671,269,76,623,572,535,146,132
38,Autoclave,490038,350 Inotech autoclave.,31,915,697,432,909,732,399,303,816,750,708,817,425
39,Autoclave,490039,608A autoclave. 120 or 208 v 8x8x16,97,657,74,91,857,214,800,580,220,217,654,742,938
40,Autoclave,490040,8816 steam powered autoclave.,91,327,575,571,139,888,999,629,806,823,574,387,841
41,Autoclave,490041,agle 901 autoclave. (needs part),46,92,428,564,287,719,717,954,510,973,494,933,909
42,Autoclave,490042,agle Ten+ tabletop sterilizer.,74,15,849,506,262,263,879,451,364,452,533,98,100
43,Autoclave,490043,Electronic portable tabletop sterilizer with b...,68,330,700,260,535,596,278,287,717,118,823,456,622
44,Autoclave,490044,floor model autoclave with 11x10x24 inch deep ...,82,443,624,118,56,893,192,331,439,400,641,150,892
45,Autoclave,490045,floor model steam sterilizer with 20 inch x 20...,2,820,715,90,736,245,731,671,968,656,980,20,363
46,Autoclave,490046,Model 8080 bench top steam sterilizer with 8x8...,30,193,181,757,690,880,209,430,325,598,630,770,452
47,Autoclave,490047,Model 1000R autoclave with recorder.,33,376,550,365,544,632,874,367,665,129,427,719,149
48,Autoclave,490048,Model 3021 single door autoclave with 20 inch ...,79,603,548,280,867,880,885,715,494,679,263,131,123
49,Autoclave,490049,Model 4520 2 door autoclave. GMP vac with bio,61,711,186,220,702,385,327,695,85,594,579,591,586

In [24]:
inventory.tail(5)

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
820,Ultrasonic Cleaners,490820,Model 221 ultrasonic cleaning bath with timer....,1,269,846,229,829,634,760,440,481,469,688,540,5
821,Ultrasonic Cleaners,490821,Model 75HT Aquasonic stainless steel ultrasoni...,32,605,584,947,748,274,385,768,296,909,33,93,965
822,Ultrasonic Cleaners,490822,Model B-22 ultrasonic cleaning bath with 9 1/2...,4,488,190,480,582,372,899,490,115,864,245,264,234
823,Ultrasonic Cleaners,490823,Model FS-28 11 quart capacity ultrasonic clean...,88,867,182,387,914,659,404,651,849,403,871,188,644
824,Ultrasonic Cleaners,490824,"SE-40 ultrasonic cleaner 6"" x 6"" x 3"" deep ch...",20,698,233,893,483,798,688,27,432,882,877,287,56

In [26]:
inventory.dtypes

In [27]:
inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Category          825 non-null    object
 1   Product Number    825 non-null    int64
 2   Description       825 non-null    object
 3   Quantity on-hand  825 non-null    int64
 4   January           825 non-null    int64
 5   February          825 non-null    int64
 6   March             825 non-null    int64
 7   April             825 non-null    int64
 8   May               825 non-null    int64
 9   June              825 non-null    int64
 10  July              825 non-null    int64
 11  August            825 non-null    int64
 12  September         825 non-null    int64
 13  October           825 non-null    int64
 14  November          825 non-null    int64
 15  December          825 non-null    int64
dtypes: int64(14), object(2)
memory usage: 103.2+ KB

In [30]:
inventory.shape[1]

16

In [31]:
inventory.describe()

,Product Number,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
count,825.00000,825.000000,825.000000,825.000000,825.000000,825.000000,825.000000,825.000000,825.000000,825.000000,825.000000,825.000000,825.000000,825.000000
mean,490412.00000,49.969697,518.181818,512.168485,504.130909,508.958788,500.183030,509.232727,497.160000,508.621818,496.298182,491.192727,500.310303,500.413333
std,238.30128,29.038020,288.794512,286.540195,290.389080,296.298538,289.363461,283.182973,293.038698,293.211383,295.090279,288.767834,295.824524,292.250188
min,490000.00000,0.000000,0.000000,5.000000,0.000000,1.000000,2.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,4.000000
25%,490206.00000,24.000000,274.000000,273.000000,261.000000,255.000000,251.000000,269.000000,229.000000,275.000000,226.000000,249.000000,239.000000,234.000000
50%,490412.00000,49.000000,524.000000,525.000000,500.000000,514.000000,499.000000,512.000000,504.000000,513.000000,490.000000,489.000000,508.000000,510.000000
75%,490618.00000,76.000000,775.000000,749.000000,753.000000,782.000000,737.000000,752.000000,755.000000,772.000000,754.000000,742.000000,753.000000,775.000000
max,490824.00000,100.000000,999.000000,999.000000,997.000000,999.000000,999.000000,999.000000,997.000000,999.000000,997.000000,998.000000,999.000000,999.000000

In [32]:
inventory.head()

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
0,Analyzer,490000,Microtrac particle analyzer (3 pcs),31,337,186,457,509,946,444,621,861,442,975,735,977
1,Analyzer,490001,3300 IR gas analyzer,68,855,837,347,769,289,907,785,815,851,270,521,244
2,Analyzer,490002,TGA-7 thermogravitmetric analyzer.,90,805,590,489,536,662,237,154,240,592,474,780,864
3,Analyzer,490003,Model 911 Dew-All digital humidity analyzer.,57,178,769,438,556,717,94,832,717,545,268,47,68
4,Analyzer,490004,1000 tablet? Hardness Tester,3,154,45,859,180,729,486,862,33,955,497,20,121

In [34]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 25.4 MB/s eta 0:00:00
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: pip install --upgrade pip

In [35]:
inventory.to_excel('inventory.xlsx', sheet_name='inventory', index=False)

In [4]:
df = inventory

In [5]:
df.columns

Index(['Category', 'Product Number', 'Description', 'Quantity on-hand',
       'January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype='object')

In [8]:
df['Description']

In [11]:
df2 = df[['Category', 'Product Number', 'Description']]

In [12]:
df2

,Category,Product Number,Description
0,Analyzer,490000,Microtrac particle analyzer (3 pcs)
1,Analyzer,490001,3300 IR gas analyzer
2,Analyzer,490002,TGA-7 thermogravitmetric analyzer.
3,Analyzer,490003,Model 911 Dew-All digital humidity analyzer.
4,Analyzer,490004,1000 tablet? Hardness Tester
...,...,...,...
820,Ultrasonic Cleaners,490820,Model 221 ultrasonic cleaning bath with timer....
821,Ultrasonic Cleaners,490821,Model 75HT Aquasonic stainless steel ultrasoni...
822,Ultrasonic Cleaners,490822,Model B-22 ultrasonic cleaning bath with 9 1/2...
823,Ultrasonic Cleaners,490823,Model FS-28 11 quart capacity ultrasonic clean...
824,Ultrasonic Cleaners,490824,"SE-40 ultrasonic cleaner 6"" x 6"" x 3"" deep ch..."

In [13]:
df.columns

Index(['Category', 'Product Number', 'Description', 'Quantity on-hand',
       'January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype='object')

In [21]:
df[(df['Quantity on-hand'] > 99) | (df['Quantity on-hand'] < 1) ]

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
35,Autoclave,490035,Validar Plus tabletop sterilizer.,0,514,801,695,632,114,499,65,849,271,877,212,430
119,Balances,490119,Model H51 electronic analytical balance with 0...,0,236,162,328,662,81,419,984,752,506,319,26,567
154,Bath,490154,250 hi temperature water bath. 37-100oc,0,694,643,3,892,778,405,279,678,644,426,445,583
265,Biohood,490265,4' wide labgard NU 440-400 class IIA2 tabletop...,100,972,997,528,2,592,73,39,610,462,952,116,274
406,Centrifuges,490406,8R (tabletop refrigerated centrifuge) w/216 ro...,100,827,341,775,938,574,155,741,615,338,123,768,35
452,Centrifuges,490452,GS-15R tabletop refrigerated centrifuge with 4...,0,230,538,373,810,495,410,390,746,198,178,125,357
509,Centrifuges,490509,Model CL tabletop centrifuge with Model 801 fi...,0,435,563,338,626,765,240,125,988,753,415,69,669
519,Centrifuges,490519,Model MP4R bench top refrigerated centrifuge w...,0,551,457,482,491,2,973,537,989,101,87,27,678
549,Centrifuges,490549,RT6000B with H1000B rotor. Refrigerated tablet...,0,702,895,870,47,775,515,994,292,470,411,222,248
589,Chromatography,490589,AKTA FPLC system with pump M925 gradient mixer...,0,39,673,787,621,58,535,868,67,364,203,657,528
639,Evaporators,490639,Model R114 rotary evaporator system complete w...,0,236,382,541,160,431,535,773,847,67,951,858,225

In [26]:
df[(df['Quantity on-hand'] > 95) & (df['January'] > 900)]

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
14,Analyzer,490014,B-641 thermal cycler,98,917,856,437,474,928,577,752,772,721,66,918,533
81,Balances,490081,balances Models DWM DLT2. 120 gram capacity.,96,949,726,951,945,158,165,127,900,750,268,518,461
212,Bath,490212,Model 230A 12 x 26 bath.,97,903,337,868,156,183,638,522,60,224,785,985,49
265,Biohood,490265,4' wide labgard NU 440-400 class IIA2 tabletop...,100,972,997,528,2,592,73,39,610,462,952,116,274
398,Centrifuges,490398,nac with 24 place rotor.,99,968,491,238,518,905,632,400,482,558,571,135,826
607,Chromatography,490607,UV-1 monitor with 254 nm filter.,98,925,175,867,992,384,912,633,237,168,39,976,686
738,Microscopes,490738,Optical 4 head teaching microscope (w/o AO 10),96,913,379,29,903,751,94,241,426,801,65,996,302

In [30]:
df[df['Quantity on-hand'].isin([10, 50,80, 90, 70, 100])]

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
2,Analyzer,490002,TGA-7 thermogravitmetric analyzer.,90,805,590,489,536,662,237,154,240,592,474,780,864
6,Analyzer,490006,343 flame analyzer - parts,90,941,303,572,172,120,900,971,500,719,348,462,714
26,Analyzer,490026,Semi-Automatic Cleveland Open Cup (ASTM D92) a...,90,275,751,159,315,459,38,342,705,833,761,290,42
33,Autoclave,490033,"OCR autoclave. 9"" diameter x 18"".",10,475,86,464,859,439,968,547,740,321,123,932,458
105,Balances,490105,Model 33 digital microbalance with 1 microgram...,90,106,294,652,518,814,632,384,504,492,549,94,515
129,Balances,490129,PC440 electronic top loading balance dual ran...,50,443,350,705,686,865,803,168,405,104,122,40,866
164,Bath,490164,dual chamber water bath with digital readout. ...,70,693,358,327,832,18,43,166,49,349,182,133,956
182,Bath,490182,M Model LTB-ATS-C Liquid to liquid thermal sho...,50,822,77,422,11,381,660,789,645,328,179,964,169
201,Bath,490201,Model 18052 digital readout aqua bath 3.1 lit...,10,908,714,36,266,960,933,31,327,653,882,738,784
257,Biohood,490257,bench top horizontal laminar flow hood/cleanbe...,70,199,812,121,16,178,917,13,782,828,781,557,403
265,Biohood,490265,4' wide labgard NU 440-400 class IIA2 tabletop...,100,972,997,528,2,592,73,39,610,462,952,116,274
284,Biohood,490284,Nua 425-600 Class IIA biohood without stand.,80,746,699,939,555,401,841,132,873,682,719,924,579
304,Cell Disrupters,490304,micro dismembrator U,90,561,787,224,19,101,962,81,743,873,641,689,328
325,Cell Disrupters,490325,Turax T45 cell disrupter,10,312,993,573,166,715,735,452,826,67,439,385,778
332,Cell Harvesters,490332,cell fusion system,90,734,393,402,468,495,63,831,309,558,254,68,558
372,Centrifuges,490372,HC Mod 2246,80,788,236,225,172,448,972,398,501,723,871,188,940
378,Centrifuges,490378,HSR8 for HSC10KA,70,732,654,341,478,7,223,538,93,268,335,180,88
402,Centrifuges,490402,J-25 high speed (20 000 rpm) refrigerated fl...,50,250,777,306,335,27,593,261,567,55,217,868,847
406,Centrifuges,490406,8R (tabletop refrigerated centrifuge) w/216 ro...,100,827,341,775,938,574,155,741,615,338,123,768,35
455,Centrifuges,490455,GS-6KR refrigerated kneewell model centrifuge ...,50,323,969,681,585,737,409,581,975,69,548,109,914
478,Centrifuges,490478,JS12 rotor,10,639,824,910,458,396,98,507,428,700,252,898,800
524,Centrifuges,490524,Model SC210 Plus Speedvac centrifuge with four...,80,946,829,276,735,681,22,724,280,1,67,221,920
539,Centrifuges,490539,RC2B centrifuge,70,816,894,547,808,14,963,45,56,221,818,498,588
546,Centrifuges,490546,RC5B floor model high speed refrigerated cent...,80,447,890,109,932,277,881,786,5,569,394,509,482
568,Centrifuges,490568,T-885 ultracentrifuge rotor.,70,929,511,679,754,437,326,113,904,731,492,532,906
587,Chromatography,490587,2138 Uvicord S monitor,90,560,956,947,120,772,114,177,610,233,420,682,607
602,Chromatography,490602,P500 pump,10,564,684,587,565,436,983,604,767,489,462,553,389
611,Desiccators,490611,plastic vacuum dessicator with cover and plate,90,886,342,8,238,984,581,155,856,305,993,422,799
615,Desiccators,490615,18x 18 inch plastic dessicator cabinet 2 comp...,90,763,419,941,395,850,708,698,662,137,83,106,716
647,Evaporators,490647,Multivap Model 114,10,892,904,478,145,473,388,56,293,721,428,572,967
649,Evaporators,490649,N-Evap Model 111 complete with bath.,70,506,828,724,410,20,26,937,386,937,328,275,703
665,Fermentors,490665,520 bench top airlift 5 liter fermenter,10,128,639,518,366,407,93,629,971,138,43,526,314
670,Fermentors,490670,System 1 cell culture,50,495,721,731,190,141,143,290,684,214,737,125,642
678,Gas Chromatographs,490678,Model N611-9000-1023-2 autosystem gas chromato...,50,755,132,194,791,135,878,560,707,349,505,718,80
686,Gas Chromatographs,490686,LSC-2 purge and trap,10,124,579,610,987,138,315,226,595,193,41,582,426
716,Microscopes,490716,50 phase contrast microscope with 32X phase ...,50,543,624,502,247,986,178,458,406,483,843,905,610
793,Spectrophotometers,490793,260 uv spectrophotometer.,80,709,533,738,992,917,406,315,955,930,117,159,878
794,Spectrophotometers,490794,295 spectrophotometer.,50,190,136,880,718,667,469,818,369,971,657,360,110
819,Ultrasonic Cleaners,490819,Model 2200 ultrasonic cleaning bath with 5 1/2...,50,465,67,516,664,716,433,107,450,218,581,756,105

- df[]: either rows or columns
- df.loc[]: both rows and columns based on location labels
- df.iloc[]: both rows and columns based on location index

In [33]:
df.loc[df['Quantity on-hand'] > 99, ['Category', 'Product Number', 'Description', 'Quantity on-hand','January']]

,Category,Product Number,Description,Quantity on-hand,January
265,Biohood,490265,4' wide labgard NU 440-400 class IIA2 tabletop...,100,972
406,Centrifuges,490406,8R (tabletop refrigerated centrifuge) w/216 ro...,100,827

In [31]:
df.columns

Index(['Category', 'Product Number', 'Description', 'Quantity on-hand',
       'January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype='object')

In [34]:
df.head(5)

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
0,Analyzer,490000,Microtrac particle analyzer (3 pcs),31,337,186,457,509,946,444,621,861,442,975,735,977
1,Analyzer,490001,3300 IR gas analyzer,68,855,837,347,769,289,907,785,815,851,270,521,244
2,Analyzer,490002,TGA-7 thermogravitmetric analyzer.,90,805,590,489,536,662,237,154,240,592,474,780,864
3,Analyzer,490003,Model 911 Dew-All digital humidity analyzer.,57,178,769,438,556,717,94,832,717,545,268,47,68
4,Analyzer,490004,1000 tablet? Hardness Tester,3,154,45,859,180,729,486,862,33,955,497,20,121

In [38]:
# the first two rows
df.iloc[0:2]
df.iloc[:2]

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
0,Analyzer,490000,Microtrac particle analyzer (3 pcs),31,337,186,457,509,946,444,621,861,442,975,735,977
1,Analyzer,490001,3300 IR gas analyzer,68,855,837,347,769,289,907,785,815,851,270,521,244

In [39]:
# the third to the fifth
df.iloc[2:5]

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
2,Analyzer,490002,TGA-7 thermogravitmetric analyzer.,90,805,590,489,536,662,237,154,240,592,474,780,864
3,Analyzer,490003,Model 911 Dew-All digital humidity analyzer.,57,178,769,438,556,717,94,832,717,545,268,47,68
4,Analyzer,490004,1000 tablet? Hardness Tester,3,154,45,859,180,729,486,862,33,955,497,20,121

In [40]:
df.iloc[:3, :4]

,Category,Product Number,Description,Quantity on-hand
0,Analyzer,490000,Microtrac particle analyzer (3 pcs),31
1,Analyzer,490001,3300 IR gas analyzer,68
2,Analyzer,490002,TGA-7 thermogravitmetric analyzer.,90

In [41]:
df.iloc[-3:, -4:]

,September,October,November,December
822,864,245,264,234
823,403,871,188,644
824,882,877,287,56

In [42]:
df.iloc[::2, :]

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
0,Analyzer,490000,Microtrac particle analyzer (3 pcs),31,337,186,457,509,946,444,621,861,442,975,735,977
2,Analyzer,490002,TGA-7 thermogravitmetric analyzer.,90,805,590,489,536,662,237,154,240,592,474,780,864
4,Analyzer,490004,1000 tablet? Hardness Tester,3,154,45,859,180,729,486,862,33,955,497,20,121
6,Analyzer,490006,343 flame analyzer - parts,90,941,303,572,172,120,900,971,500,719,348,462,714
8,Analyzer,490008,9000 analyzer,22,339,879,902,530,142,442,813,8,725,185,47,743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816,Ultrasonic Cleaners,490816,B220 ultrasonic cleaning bath. 5 1/2 x 9 x 4 i...,99,601,83,71,120,107,403,178,392,808,265,165,777
818,Ultrasonic Cleaners,490818,Model 1210R - DTH ultrasonic cleaning bath wit...,54,738,76,361,27,370,813,992,209,120,468,357,332
820,Ultrasonic Cleaners,490820,Model 221 ultrasonic cleaning bath with timer....,1,269,846,229,829,634,760,440,481,469,688,540,5
822,Ultrasonic Cleaners,490822,Model B-22 ultrasonic cleaning bath with 9 1/2...,4,488,190,480,582,372,899,490,115,864,245,264,234
824,Ultrasonic Cleaners,490824,"SE-40 ultrasonic cleaner 6"" x 6"" x 3"" deep ch...",20,698,233,893,483,798,688,27,432,882,877,287,56

In [43]:
df.iloc[1::2, :]

,Category,Product Number,Description,Quantity on-hand,January,February,March,April,May,June,July,August,September,October,November,December
1,Analyzer,490001,3300 IR gas analyzer,68,855,837,347,769,289,907,785,815,851,270,521,244
3,Analyzer,490003,Model 911 Dew-All digital humidity analyzer.,57,178,769,438,556,717,94,832,717,545,268,47,68
5,Analyzer,490005,213 blood gas analyzer with 208 -02/01,35,441,349,820,519,309,469,31,68,603,188,82,810
7,Analyzer,490007,513 blood gas analyzer,82,673,86,604,269,606,236,594,27,585,723,741,674
9,Analyzer,490009,903-H moisture analog,31,767,684,279,743,231,785,987,440,816,472,343,858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815,Ultrasonic Cleaners,490815,9332 ultrasonic cleaner,93,802,550,38,44,279,783,133,61,492,921,761,237
817,Ultrasonic Cleaners,490817,console BC 300-126-6 cleaner,29,367,602,647,540,527,734,519,525,700,525,524,884
819,Ultrasonic Cleaners,490819,Model 2200 ultrasonic cleaning bath with 5 1/2...,50,465,67,516,664,716,433,107,450,218,581,756,105
821,Ultrasonic Cleaners,490821,Model 75HT Aquasonic stainless steel ultrasoni...,32,605,584,947,748,274,385,768,296,909,33,93,965
823,Ultrasonic Cleaners,490823,Model FS-28 11 quart capacity ultrasonic clean...,88,867,182,387,914,659,404,651,849,403,871,188,644